kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: quarto-example-name
  namespace: nada
  labels:
    team: nada
spec:
  image: {{ image }}
  env:
    - name: GCS_QUARTO_BUCKET
      value: example-bucket-name
    - name: QUARTO_UUID
      value: "example-uuid"
    - name: QUARTO_PATH
      value: "example-path"
  ingresses:
    - https://data.ansatt.nav.no/example-path
  replicas:
    min: 1
    max: 2
