kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: quarto-overgangsindikator
  namespace: nada
  labels:
    team: nada
spec:
  image: {{ image }}
  env:
  - name: GCS_QUARTO_BUCKET
    value: ovind_bucket
  - name: QUARTO_UUID
    value: ""
  - name: QUARTO_PATH
    value: "overgangsindikator"
  ingresses:
  - https://data.intern.nav.no/overgangsindikator
  replicas:
    min: 1
    max: 2
