kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: nada-quarto-proxy
  namespace: nada
  labels:
    team: nada
spec:
  image: {{ image }}
  env:
    - name: GCS_QUARTO_BUCKET
      value: nada-quarto-odata-dev
    - name: QUARTO_UUID
      value: c41cb620-546f-4001-b2c4-1db5168d202b
    - name: QUARTO_PATH
      value: "omverdensanalyse"
  ingresses:
    - https://data.nav.no
  replicas:
    min: 2
    max: 3
