name: update-quarto
on: 
  push:
    branches:
      - '*'

jobs:
  update-quarto:
    name: Update quarto story
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Upload files
        working-directory: _site
        run: gsutil cp -r * gs://nada-quarto-odata-dev/123/
